version: 2.1
orbs:
  docker: circleci/docker@1.6.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      node-type:
          default: "t2.micro"
          description: |
              Set this to specify a node instance type for the node group.
          type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/capstone-project

  verify-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
            kubectl get pods  
          name: Verify cluster

workflows:
  default:
    jobs:
      #- build
      - docker/hadolint:
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: 'DL4005,DL3008'
      - docker/publish:
          image: 4servnet/capstone
          use-docker-credentials-store: true
          tag: latest   
          requires:
            - docker/hadolint