version: 2.1
orbs:
  docker: circleci/docker@1.6.0
jobs:
  build:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
workflows:
  default:
    jobs:
      #- build
      - docker/hadolint:
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: 'DL4005,DL3008'
#      - docker/publish:
#          image: 4servnet/capstone-test
#          use-docker-credentials-store: true