version: 2.1
orbs:
  docker: circleci/docker@1.6.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      node-type:
          default: "t2.micro"
          description: |
              Set this to specify a node instance type for the node group.
          type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/capstone-project

workflows:
  default:
    jobs:
      - create-deployment:
          cluster-name: capstonepro
      - aws-eks/update-container-image:
          cluster-name: capstonepro
          container-image-updates: 'capstone-project=4servnet/capstone-test'
          post-steps:
            - kubernetes/delete-resource:
                resource-names: capstone-project
                resource-types: deployment
                wait: true
          record: true
          requires:
            - create-deployment
          resource-name: deployment/capstone-project
      - aws-eks/delete-cluster:
          cluster-name: capstonepro
          requires:
            - aws-eks/update-container-image